### ISSUE TITLE
Can't continue installation process

### ISSUE THREAD

**Issue by Drsheppard01** [Nitrux/calamares-settings-nitrux#13]
Calamares will not let you in if the connection is not wired but wi-fi. The only permissible step is to select the language. Then you can't. 

https://gist.github.com/Drsheppard01/dc93cc27ee6b1874607a30faf168d439

**Comment by UriHerrera** [comment]
It's mentioned in the [Notes](https://nxos.org/notes/notes-nitrux-2-7-1/#installing-nitrux) that _the installation process requires an active internet connection_. Wireless networks need to be added manually by the user by selecting a network and authenticating to that network; Ethernet connections are automatically set up.

Therefore, it's not a bug.

**Comment by Drsheppard01** [comment]
I am using an Asus X415JA laptop. It doesn't have an RJ-45 port (for Ethernet cable). So the only way to establish a wired connection is via USB by tethering, but since the speed of this transfer is significantly lower, it does not solve the problem, but creates additional costs. I would really like to try Nitrux, but apparently I don't have that option

**Comment by UriHerrera** [comment]
Your laptop has a wireless chip, correct?; you can simply connect to a wireless network **_before_** launching Calamares, right? Because that's what I understand is the problem, that you run Calamares without connecting to a network. So because you're not connected to the internet, Calamares can't perform this mandatory check, so you can't continue, yes?

Absolutely no operating system connects automatically to unknown, unauthenticated wireless networks by itself, and by default, that's not normal behavior.

Or what am I not understanding about the problem? Does the wireless in your laptop not work? Is it not recognized by the distribution? Why are you not using the wireless chip in your laptop to connect to a wireless network?

To be clear, _**an active internet connection is mandatory;**_ what is not mandatory is an Ethernet connection or a wired connection; you can connect to a wireless network and continue with the installation.

**Comment by Drsheppard01** [comment]
1. Is it possible for calamares to periodically check the connection?
2. The first time I tried it on Maui Shell 2.7.0 when I clicked on the wi-fi SSID in the network settings widget nothing happened (no password field was displayed)

**Comment by UriHerrera** [comment]
1. No, Calamares checks the internet connection once. If you think Calamares should be constantly checking, you can create an issue at [their repository](https://github.com/calamares/calamares/issues).
2. If you experienced an issue with Maui Shell, create a new issue at the Maui Shell repository.

Please open separate issues for different problems.
