### ISSUE TITLE
Nitrux live CD image installer issues in virtual machine VMWare Workstation or player v1.0.7-4

### ISSUE THREAD

**Issue by wpostma** [Nitrux/calamares-settings-nitrux#4]
Nitrux live CD image installer has issues when installed from a virtual machine like VMWare 

From within a virtual machine, or on a physical PC with a resolution of around 1280x1024 or less, the installer appearance is marred by not being maximized. You can see in the screenshot that a user can't see the Next button because it's off the bottom of either the physical monitor, or the virtual screen if it is being installed into a virtual machine.

Exacerbating the confusion is that it's possible to manually maximize this installer (which is odd since most installers just take over and always go kiosk mode and hide the desktop), but the installer window's maximize widget looks unlike anything I've ever seen. It would be more user friendly to just go full screen and then show a reasonable icon that means "exit fullscreen" if you mouse hover over the top right corner.  The usual icon for this is:

http://fontawesome.io/3.2.1/icon/fullscreen/

The installer showing the cropped (nearly invisible) Next button (due to default window height being taller than my vmware vm screen resolution):

![installer_on_live_image_should_be_maximized_or_should_be_smaller_by_default](https://user-images.githubusercontent.com/1833470/35451862-7eb36756-0279-11e8-88ee-13d8da2b835f.png)

Installers are uniquely constrained environments. You may notice that assumptions on minimum screen resolution need to be quite conservatively assessed when building installers. These days even physical hardware is not the only consideration. Most users will try Nitrux first from inside a virtual machine or hyperviser system, such as qemu/kvm, vmware, virtualbox, etc.

After the first installation, the system boots to a black screen with a full screen keyboard. This is probably not intentional. Clicking on the full screen onscreen keyboard (appears to be for tablet access) will reveal a greeter screen with username and password input boxes.  This is an extremely odd decision.

Even odder, while it seems some effort to be tablet-friendly has been made this has resulted in Nitrux being unusable from a virtual machine with a keyboard and a mouse.

Complete inability to focus and type into the password box WITH A KEYBOARD is a surprising move on your installer.
  
Thus ends my attempt to learn about Nitrux OS. It's not ready to log into yet:

![the_what](https://user-images.githubusercontent.com/1833470/35452232-ba0d96a4-027a-11e8-8e8c-dccc6d9fb200.png)

The above picture could be explained by the video driver in the linux kernel doing something odd here.

After trying the above several times I notice:

1. You can type into the input boxes but the screen doesn't show any input at all (does not refresh). If you type your user name and tab, and then password and tab key and then press login you can log in. This persists even if you change compositor settings.

2. All the while there is no visible indication that your keystrokes are even accepted.

After 15 minutes I managed to log into the login screen. Note that VMWare Workstation Player does not offer me any way to experiment with alternative video.   lspci reports
VGA compatible controller: VMware SVGA II Adapter as my video card type from inside Nitrux.

If there's somewhere ELSE I should log a but about a posssible bug with your Linux 4.13 kernel, plus this video card type, when used with your QT+Nomad desktop, LMK and I'll log a second bug and provide any details to reproduce.

This bad behaviour is reproducible no matter what Compositor setting (OpenGL3,2, or XRender) is selected.  There is somethign fundamentally unworkable about your compositor engine configuration out of box with Nitrux, Plasma/QT/KDE and its compositor, and this videocard.   This bad behaviour is visible even when you hit Ctrl+Alt+F1 and log into a text login in Nitrux, within vmware.  It seems this 4.13 kernel's VMWare video driver doesn't work with VMWare Workstation 14.

[ reopened here, because it was originally incorrectly posted at: https://github.com/Nitrux/nxs/issues/1 ]

**Comment by star-buck** [comment]
@Uri: I think current Calamres maintainer Adriaan would welcome any overall
design input, it would indeed make Nitrux look so much more professional if
you did a polished calamares update to it.

**Comment by azubieta** [comment]
I'm experiencing a similar error but in the login screen.
This came up with the latest update so I suspect that it not only NXOS related.

**Comment by wpostma** [comment]
What video driver is on your system? @azubieta

**Comment by wpostma** [comment]
The QT/Plasma LOCK screen does not have the glitches that this login/greeter/sddm does.

**Comment by UriHerrera** [comment]
Thanks for your thorough feedback, it's very much appreciated.

Covering the first part of this issue about the installer. I believe we can do something about the size of the window when Calamares is started through our settings package (what's in this repository).

When the user boots to the Live session it's allowed to test-drive the system. The mode you're referring to which boots straight to the installer instead of the Live session is disabled in the bootloader. This is for 2 reasons, 1) Calamares doesn't (seem to) support this mode unlike other installers like Ubiquity (what Ubuntu and most Ubuntu-based distributions use) and 2) because it'd be preferable for the user to use the system; explore it and then decide to install it rather than jump straight into the installer.

As you correctly point out, most new users will try Nitrux on a virtual machine. We include the guest additions package of VirtualBox for this purpose but we don't include the VMWare tools package; which is why you'd get a 1280x1024/1024x768/800x640 window and no OpenGL acceleration. We could include the software at some point but we'd have to test it for compatibility with other software like Vbox's stuff first.

Covering the second part of this issue about the display manager. The virtual keyboard that you see is the Qt Virtual Keyboard. This is however not a configuration done from our part, this is a bug with SDDM or the file that SDDM uses to load it's configuration. This happens because it seems that in a recent update of SDDM support for multiple input methods such as virtual keyboards was introduced, however the configuration file in `/etc/sddm.conf` is missing the string that SDDM needs to select a preferred input method so it defaults to the virtual keyboard, this is fixed in Nitrux 1.0.8.

Covering the third part of this issue about the virtual keyboard. As far as I know it's meant to be used in Wayland. We don't currently ship Wayland so that's probably why it looks broken. As we don't purposely use the virtual keyboard for anything in particular or at all it'd would be a bug meant for upstream (Qt).

Covering the fourth part of this issue about VMWare Player. Your video issues are most likely than not because VMWare Tools aren't installed. As per your `lspci` output `VGA compatible controller: VMware SVGA II Adapter` is the emulated VGA hardware that VMWare uses. It's worth noting that you should allocate as much video memory to the VM as possible. Most modern GPUs can address well over 1 GB of VRAM, I'd recommend you to allocate 128 MB to the virtual machine, [VMWare also recommends doing so](https://kb.vmware.com/s/article/1007140). The OpenGL support in VMWare is quite better than in VirtualBox but given that it's still emulated hardware using XRender is the only way to go.

--------

For issues/suggestions/bugs/ about the theming (Plasma theme; Aurorae theme; Color schemes; Konsole theme; SDDM theme) go here: https://github.com/nomad-desktop/nomad-plasma-look-and-feel

For issues/suggestions/bugs/ about the widget theming (buttons, window widgets) go here: https://github.com/nomad-desktop/nomad-kvantum-theme

Thanks for trying out Nitrux!.

**Comment by UriHerrera** [comment]
@star-buck I agree that Calamares needs an UI update. I'll contact the developer.
